Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.9.6/x64/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/opt/hostedtoolcache/Python/3.9.6/x64/lib/python3.9/site-packages/nbclient/client.py", line 1112, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/hostedtoolcache/Python/3.9.6/x64/lib/python3.9/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/opt/hostedtoolcache/Python/3.9.6/x64/lib/python3.9/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/opt/hostedtoolcache/Python/3.9.6/x64/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/opt/hostedtoolcache/Python/3.9.6/x64/lib/python3.9/site-packages/nbclient/client.py", line 553, in async_execute
    await self.async_execute_cell(
  File "/opt/hostedtoolcache/Python/3.9.6/x64/lib/python3.9/site-packages/nbclient/client.py", line 857, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/opt/hostedtoolcache/Python/3.9.6/x64/lib/python3.9/site-packages/nbclient/client.py", line 760, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
A = [[18,2],[-2,10]]
LUNaive(A)
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mAttributeError[0m                            Traceback (most recent call last)
[0;32m/tmp/ipykernel_1938/2944131217.py[0m in [0;36m<module>[0;34m[0m
[1;32m      1[0m [0mA[0m [0;34m=[0m [0;34m[[0m[0;34m[[0m[0;36m18[0m[0;34m,[0m[0;36m2[0m[0;34m][0m[0;34m,[0m[0;34m[[0m[0;34m-[0m[0;36m2[0m[0;34m,[0m[0;36m10[0m[0;34m][0m[0;34m][0m[0;34m[0m[0;34m[0m[0m
[0;32m----> 2[0;31m [0mLUNaive[0m[0;34m([0m[0mA[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m
[0;32m/tmp/ipykernel_1938/41586813.py[0m in [0;36mLUNaive[0;34m(A)[0m
[1;32m     17[0m     [0mnb[0m [0;34m=[0m [0mn[0m[0;34m+[0m[0;36m1[0m[0;34m[0m[0;34m[0m[0m
[1;32m     18[0m     [0;31m# Gauss Elimination[0m[0;34m[0m[0;34m[0m[0;34m[0m[0m
[0;32m---> 19[0;31m     [0mU[0m [0;34m=[0m [0mA[0m[0;34m.[0m[0mastype[0m[0;34m([0m[0mfloat[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m     20[0m     [0mL[0m [0;34m=[0m [0mnp[0m[0;34m.[0m[0meye[0m[0;34m([0m[0mn[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m     21[0m [0;34m[0m[0m

[0;31mAttributeError[0m: 'list' object has no attribute 'astype'
AttributeError: 'list' object has no attribute 'astype'

